package edu.loyola.cs485.model.dao;

import edu.loyola.cs485.model.entity.Client;
import java.sql.*;

public class ClientDAO extends AbstractDAO<Client> {
    @Override
    public void create(Client entity) throws SQLException {
        Connection con = getConnection(); // Always open a connection

        String sql = "INSERT INTO Client (name_client, email, dob) VALUES (?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);
        pst.setString(1, entity.getName());
        pst.setString(2, entity.getEmail());
        pst.setDate(3, entity.getDob() );
        pst.executeUpdate();

        ResultSet rs = pst.getGeneratedKeys();
        if (rs.next()) {
            entity.setID(rs.getInt(1));
        }

        con.close(); // Dont forget to close it
    }

    @Deprecated
    public void createVersion1(Client entity) throws SQLException {
        Connection con = getConnection();

        String sql = "INSERT INTO Client (name_client, email, dob) VALUES (?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, entity.getName());
        pst.setString(2, entity.getEmail());
        pst.setDate(3, entity.getDob() );
        pst.executeUpdate();
        // What was the value of the autogenerated PK?
        con.close();
    }

    @Override
    public Client read(int ID) throws SQLException {
        Client readClient = new Client();
        Connection con = getConnection();

        String sql = "SELECT * FROM client WHERE id_client = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, ID);
        ResultSet Rs = pst.executeQuery();
        if (Rs.next()) { //IF because there should be 1 or 0 results
            readClient.setID( Rs.getInt("id_client") );
            readClient.setName( Rs.getString("name_client") );
            readClient.setEmail( Rs.getString("email") );
            readClient.setDob( Rs.getDate("dob") );
        }

        con.close();
        return readClient;
    }

    @Override
    public void update(Client entity) throws SQLException {
        // Exercise 1
    }

    @Override
    public void delete(int ID) throws SQLException {
        Connection con = getConnection();
        String sql = "DELETE FROM client WHERE id_client = ?";

        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, ID);
        pst.executeUpdate();

        con.close();
    }
}
